# https://www.hackerrank.com/challenges/tutorial-intro/problem

####################################
########## sorting #################
Most sorting algorithms are comparison sorts, i.e. they sort a list just by comparing the elements to one another. 
A comparison sort algorithm cannot beat n*log(n) (worst-case) running time, since n*log(n) represents the minimum 
number of comparisons needed to know where to place each element.
http://www.cs.cmu.edu/~avrim/451f11/lectures/lect0913.pdf

Insertion Sort
----------------
$N^2$ time algorithm
staple

Quicksort (Partition Sort)
----------------
a divide-and-conquer algorithm
running time of: n*log(n) 

Counting sort
----------------
a non-comparison sorting algorithm
staple

heap sort
----------------
