#!/bin/sh
# Public Key Authentication

# https://www.digitalocean.com/community/tutorials/how-to-configure-ssh-key-based-authentication-on-a-linux-server
# https://www.digitalocean.com/community/tutorials/how-to-use-ssh-keys-with-digitalocean-droplets
# https://www.digitalocean.com/community/tutorials/initial-server-setup-with-ubuntu-16-04

# Create the RSA Key Pair (if there is one exist you could use it you don't need to make new one)
ssh-keygen -t rsa
ssh-keygen -t rsa -C "your_email@example.com"
ssh-keygen -t rsa -f cloud.key

# copy the public key into the server
# .ssh folder should be 700 and authorized_keys file should be 600
cat ~/.ssh/id_rsa.pub | ssh [username]@[server.ip.address.here] "cat >> ~/.ssh/authorized_keys"
# or, use the following to automatically copy the public key
ssh-copy-id [username]@hostname
# or, if you don't have access using password you can run the following while you are in the root
rsync --archive --chown=[username]:[username] ~/.ssh /home/[username]


# https://serverfault.com/questions/221760/multiple-public-keys-for-one-user

# the question if you have a new machine how to copy the key to it

# tunnel
ssh -L 8888:localhost:8888 qcri@qatslive4520.cloudapp.net

