#!/bin/sh

# reference : https://www.digitalocean.com/community/tutorials/initial-server-setup-with-ubuntu-16-04
# 123
adduser disooqi


# set up what is known as "superuser" or root privileges for our normal account. 
# This will allow our normal user to run commands with administrative privileges by putting the word sudo 
# before each command
usermod -aG sudo disooqi

# On the server, as the root user, enter the following command to temporarily switch to the new user 
# (substitute your own user name):
su - disooqi

sudo adduser <username>
sudo userdel <username>

sudo adduser <username> <group_name>
sudo deluser <username> <group_name>

sudo groupadd <group_name>
sudo groupdel <group_name>


4 = read
2 = write
1 = excute

    7               7               7 
The owner      the group       everybody_else

sudo chmod 777   file/dir   [-R]
sudo chown -R <username> file
sudo chgrp -R <group_name> file



